apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: bank.joakim.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-svc
            port: 
              number: 80
  
  tls:
   - hosts:
      - demo.joakim.online
     secretName: app
